### ISSUE TITLE
Sketch will not run 

### ISSUE THREAD

**Issue by lschotz** [protostax/ProtoStax_CapacitiveTouch_Piano_Demo#1]
I have tried to run this sketch but no luck. I have included the libraries. It seems to have problems with the term downBtn and upBtn

**Comment by sridharrajagopal** [comment]
I believe the Button library has changed names. You’ll want to check the new name and replace it. I’ll look into it when I have a moment. 

Thanks,
Sridhar

**Comment by lschotz** [comment]
Thank you I really appreciate it.

Larry

**Comment by sridharrajagopal** [comment]
The Button library I use is now called JC_Button - https://github.com/JChristensen/JC_Button

You will need to install that as well (you can do that from the Arduino IDE Library Manager directly). I will update the README to reflect that. 

You will also need to change the 
#include <Button.h>
to 
#include <JC_Button.h>

You don't need the button unless you are doing the Multi-Octave Capacitive Touch Piano - there the buttons are used to shift the octave up or down. So if you're not using the buttons, you can disable that part of the code. 

Thanks,
Sridhar

**Comment by lschotz** [comment]
Hello Sridhar

One more issue, The code stops at “playtune”

Arduino: 1.8.12 (Mac OS X), Board: "Arduino Uno"

/Users/larryschotz/Downloads/protostax-ProtoStax_CapacitiveTouch_Piano_Demo-1a250b7/ProtoStax_CapacitiveTouch_Piano_Demo/ProtoStax_CapacitiveTouch_Piano_Demo.ino: In function 'void setup()':
ProtoStax_CapacitiveTouch_Piano_Demo:166:3: error: 'playTune' was not declared in this scope
   playTune(melody2, 23, 48);
   ^~~~~~~~
/Users/larryschotz/Downloads/protostax-ProtoStax_CapacitiveTouch_Piano_Demo-1a250b7/ProtoStax_CapacitiveTouch_Piano_Demo/ProtoStax_CapacitiveTouch_Piano_Demo.ino: At global scope:
ProtoStax_CapacitiveTouch_Piano_Demo:179:5: error: expected unqualified-id before 'else'
   } else {
     ^~~~
ProtoStax_CapacitiveTouch_Piano_Demo:184:3: error: 'currtouched' does not name a type
   currtouched = cap.touched();
   ^~~~~~~~~~~
ProtoStax_CapacitiveTouch_Piano_Demo:187:3: error: expected unqualified-id before 'if'
   if (currtouched == 2193) { // C E G B
   ^~
ProtoStax_CapacitiveTouch_Piano_Demo:189:5: error: expected unqualified-id before 'else'
   } else if (currtouched == 181) { // C D E F G
     ^~~~
ProtoStax_CapacitiveTouch_Piano_Demo:191:5: error: expected unqualified-id before 'else'
   } else if (currtouched == 2565) { // C D A B
     ^~~~
ProtoStax_CapacitiveTouch_Piano_Demo:193:5: error: expected unqualified-id before 'else'
   } else if (currtouched == 3075) { // C C# A# B
     ^~~~
ProtoStax_CapacitiveTouch_Piano_Demo:195:5: error: expected unqualified-id before 'else'
   } else {
     ^~~~
ProtoStax_CapacitiveTouch_Piano_Demo:217:3: error: 'lasttouched' does not name a type
   lasttouched = currtouched;
   ^~~~~~~~~~~
ProtoStax_CapacitiveTouch_Piano_Demo:218:1: error: expected declaration before '}' token
 }
 ^
Hope you can help

Larry

**Comment by sridharrajagopal** [comment]
There are a whole bunch of errors here, not just at playTune. This looks like your indenting may be off - you might be missing a ‘{‘ or a ‘}’ someplace. 

Did you edit the code (for example, to remove the button stuff, or to add something else)?

**Comment by lschotz** [comment]
I have commented out the button part but now this is the error I get: This error is surprising because that section of the code is from the MPR121 library

Larry
Arduino: 1.8.12 (Mac OS X), Board: "Arduino Uno"

ProtoStax_CapacitiveTouch_Piano_Demo:187:3: error: 'currtouched' does not name a type
   currtouched = cap.touched();
   ^~~~~~~~~~~
ProtoStax_CapacitiveTouch_Piano_Demo:190:3: error: expected unqualified-id before 'if'
   if (currtouched == 2193) { // C E G B
   ^~
ProtoStax_CapacitiveTouch_Piano_Demo:200:6: error: expected unqualified-id before '{' token
   }  {
      ^
ProtoStax_CapacitiveTouch_Piano_Demo:222:3: error: 'lasttouched' does not name a type
   lasttouched = currtouched;
   ^~~~~~~~~~~
ProtoStax_CapacitiveTouch_Piano_Demo:223:1: error: expected declaration before '}' token
 }
 ^
Multiple libraries were found for "Button.h"
 Used: /Users/larryschotz/Documents/Arduino/libraries/Button
 Not used: /Users/larryschotz/Documents/Arduino/libraries/Button-Arduino
exit status 1
'currtouched' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sridharrajagopal** [comment]
Especially when you have some unclosed } you’ll get multiple errors. Usually it’s not really where the compiler thinks it might be. 

In your errors I also see 

ProtoStax_CapacitiveTouch_Piano_Demo:223:1: error: expected declaration before '}' token
}

This leads me to believe you might have deleted a bit too much when you removed the button code? Also make sure to delete/comment out the #include <Button.h>

Because I also see this error message:

Multiple libraries were found for "Button.h"
 Used: /Users/larryschotz/Documents/Arduino/libraries/Button
 Not used: /Users/larryschotz/Documents/Arduino/libraries/Button-Arduino

Can you send me your full code? You can email it to support@protostax.com 

Thanks,
Sridhar

**Comment by sridharrajagopal** [comment]
You can also get the code working with the button stuff easily first (and then delete the button code).

To get the code working with the button stuff, just install the JC_Button library, and the change the 
#include<Button.h> 
to
#include<JC_Button.h> 

If that compiles you know the code is ok as is. Then you can play around with removing the button code. Make sure you keep track of all indented code blocks and not remove extra code with a } by mistake, for example.

**Comment by lschotz** [comment]
Here is my code. The only error I get is 
Arduino: 1.8.12 (Mac OS X), Board: "Arduino Uno"

/Users/larryschotz/Downloads/protostax-ProtoStax_CapacitiveTouch_Piano_Demo-1a250b7/ProtoStax_CapacitiveTouch_Piano_Demo/ProtoStax_CapacitiveTouch_Piano_Demo.ino: In function 'void setup()':
ProtoStax_CapacitiveTouch_Piano_Demo:171:3: error: 'playTune' was not declared in this scope
   playTune(melody2, 23, 48);
   ^~~~~~~~
/Users/larryschotz/Downloads/protostax-ProtoStax_CapacitiveTouch_Piano_Demo-1a250b7/ProtoStax_CapacitiveTouch_Piano_Demo/ProtoStax_CapacitiveTouch_Piano_Demo.ino: In function 'void loop()':
ProtoStax_CapacitiveTouch_Piano_Demo:193:5: error: 'playTune' was not declared in this scope
     playTune(melody, MELODY_LENGTH(melody), 2); // Play Twinkle Twinkle Little Star
     ^~~~~~~~
ProtoStax_CapacitiveTouch_Piano_Demo:195:4: error: 'playTune' was not declared in this scope
    playTune(melody2, MELODY_LENGTH(melody2), 48); // Play scale slide up and down
    ^~~~~~~~
ProtoStax_CapacitiveTouch_Piano_Demo:198:4: error: 'playTune' was not declared in this scope
    playTune(melody3, MELODY_LENGTH(melody3), 1);
    ^~~~~~~~
ProtoStax_CapacitiveTouch_Piano_Demo:201:2: error: 'playTune' was not declared in this scope
  playTune(melody4, MELODY_LENGTH(melody4), 1);  // Play Frere Jacques
  ^~~~~~~~
ProtoStax_CapacitiveTouch_Piano_Demo:233:48: error: a function-definition is not allowed here before '{' token
 void playTune(Note *m, int mSize, int speedUp) {
                                                ^
ProtoStax_CapacitiveTouch_Piano_Demo:253:1: error: expected '}' at end of input
 }
 ^
exit status 1
'playTune' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.



#include <Adafruit_MPR121.h>

/*************************************************** 
  ProtoStax Capacitive Touch Piano Demo

  This is a example sketch for a Touch Piano using Arduino,  
   
  Adafruit 12 x Capacitive Touch Shield for Arduino - MPR121 --> https://www.adafruit.com/product/2024,
  Piezo Buzzer PS1240,
  Copper Foil Tape with Conductive Adhesive,
  and 
  ProtoStax for Arduino --> https://www.protostax.com/products/protostax-for-arduino

  It uses conductive copper foil tape stuck on the top of a ProtoStax for Arduino enclosure to provide a 
  one-octave piano keyboard, using the capacitive touch shield to sense touches, and playing the appropriate
  notes on a piezo buzzer. 

  The following pins are used in this example - 
  SCL and SDA pins for I2C communications with the MPR121, and pin 12 for the buzzer. This uses the tone
  library, which will also affect pins 3 and 11 (the tone library uses Timer2 which will conflict with these pins). 
  You can also use the replacement NewTone library (tone --> NewTone, and noTone --> noNewTone), which is smaller, 
  has faster execution and uses Timer1 which can resolve conflicts with pins 3 and 11 
  (but which conflicts with pins 9 and 10 instead)

  This takes some pointers from the MPR121test example sketch by Adafruit/Limor Fried.
 
  Written by Sridhar Rajagopal for ProtoStax
  BSD license. All text above must be included in any redistribution
 */


#include <Wire.h>

#include "Adafruit_MPR121.h"
#include "pitches.h"
#include "noteDurations.h"
#include<JC_Button.h> 
#ifndef _BV
#define _BV(bit) (1 << (bit)) 
#endif


const byte
  DN_PIN (3),
//Connect a tactile button switch (or something similar)
   UP_PIN (2);                        //from Arduino pin 2 to ground.
//#define  SW2     3         //Connect a tactile button switch (or something similar)
                           //from Arduino pin 3 to ground.

#define PULLUP true        //To keep things simple, we use the Arduino's internal pullup resistor.
#define INVERT true        //Since the pullup resistor will keep the pin high unless the
                           //switch is closed, this is negative logic, i.e. a high state
                           //means the button is NOT pressed. (Assuming a normally open switch.)
#define DEBOUNCE_MS 20     //A debounce time of 20 milliseconds usually works well for tactile button switches.
#define LONG_PRESS 1000    //We define a "long press" to be 1000 milliseconds.

//Button upBtn(SW1, PULLUP, INVERT, DEBOUNCE_MS);    //Declare the button
//Button downBtn(SW2, PULLUP, INVERT, DEBOUNCE_MS);    //Declare the button
//#define Button 
// pitches.h defines all the frequencies for the different notes in different octaves
// Let us pick one octave for our keyboard below, so it is easy to change it in one place
// For example, if you want to go down an octave, change NOTE_C7 to NOTE_C6 and so on

#define NOTE_C  NOTE_C7
#define NOTE_CS NOTE_CS7
#define NOTE_D  NOTE_D7
#define NOTE_DS NOTE_DS7
#define NOTE_E  NOTE_E7
#define NOTE_F  NOTE_F7
#define NOTE_FS NOTE_FS7
#define NOTE_G  NOTE_G7
#define NOTE_GS NOTE_GS7
#define NOTE_A  NOTE_A7
#define NOTE_AS NOTE_AS7
#define NOTE_B  NOTE_B7

// These correspond to the 12 physical capacitive touch keys of the Piano
// Feel free to change the mapping to your own! 
// notes in the scale:
int scale[7][12] = {
  {  NOTE_C1, NOTE_CS1, NOTE_D1, NOTE_DS1, NOTE_E1, NOTE_F1, NOTE_FS1, NOTE_G1, NOTE_GS1, NOTE_A1, NOTE_AS1, NOTE_B1 },
  {  NOTE_C2, NOTE_CS2, NOTE_D2, NOTE_DS2, NOTE_E2, NOTE_F2, NOTE_FS2, NOTE_G2, NOTE_GS2, NOTE_A2, NOTE_AS2, NOTE_B2 },
  {  NOTE_C3, NOTE_CS3, NOTE_D3, NOTE_DS3, NOTE_E3, NOTE_F3, NOTE_FS3, NOTE_G3, NOTE_GS3, NOTE_A3, NOTE_AS3, NOTE_B3 },
  {  NOTE_C4, NOTE_CS4, NOTE_D4, NOTE_DS4, NOTE_E4, NOTE_F4, NOTE_FS4, NOTE_G4, NOTE_GS4, NOTE_A4, NOTE_AS4, NOTE_B4 },
  {  NOTE_C5, NOTE_CS5, NOTE_D5, NOTE_DS5, NOTE_E5, NOTE_F5, NOTE_FS5, NOTE_G5, NOTE_GS5, NOTE_A5, NOTE_AS5, NOTE_B5 },
  {  NOTE_C6, NOTE_CS6, NOTE_D6, NOTE_DS6, NOTE_E6, NOTE_F6, NOTE_FS6, NOTE_G6, NOTE_GS6, NOTE_A6, NOTE_AS6, NOTE_B6 },
  {  NOTE_C7, NOTE_CS7, NOTE_D7, NOTE_DS7, NOTE_E7, NOTE_F7, NOTE_FS7, NOTE_G7, NOTE_GS7, NOTE_A7, NOTE_AS7, NOTE_B7 },
};

int octaveNum = 4;

// The Piezo uses pin 12 in our example. Change as needed. Remember that you cannot use pins 3 and 11 
// when using the tone library
#define TONE_PIN 12

// All of our tunes have the same characteristics 
// A Note in a melody has a frequency and a duration (1 = whole note, 2 = half note, etc)
// A melody consists of an array of such Notes (the melody)
// playTunes takes a pointer to the melody array of Notes, as well as a speedup factor. 
// The speedup factor is to facilitate playing at a higher speed (1 plays at intended speed, 
// 2 at twice the speed and so on) without having to modify the noteDurations array

typedef struct Note {
  int frequency;
  float duration;   
} Note;

// This melody is Twinkle Twinkle Little Star!

Note melody[] = { 
  {NOTE_C, NOTE_HALF}, {NOTE_C, NOTE_HALF}, {NOTE_G, NOTE_HALF}, {NOTE_G, NOTE_HALF}, {NOTE_A, NOTE_HALF}, {NOTE_A, NOTE_HALF}, {NOTE_G, NOTE_WHOLE}, 
  {NOTE_F, NOTE_HALF}, {NOTE_F, NOTE_HALF}, {NOTE_E, NOTE_HALF}, {NOTE_E, NOTE_HALF}, {NOTE_D, NOTE_HALF}, {NOTE_D, NOTE_HALF}, {NOTE_C, NOTE_WHOLE},
  {NOTE_G, NOTE_HALF}, {NOTE_G, NOTE_HALF}, {NOTE_F, NOTE_HALF}, {NOTE_F, NOTE_HALF}, {NOTE_E, NOTE_HALF}, {NOTE_E, NOTE_HALF}, {NOTE_D, NOTE_WHOLE},
  {NOTE_G, NOTE_HALF}, {NOTE_G, NOTE_HALF}, {NOTE_F, NOTE_HALF}, {NOTE_F, NOTE_HALF}, {NOTE_E, NOTE_HALF}, {NOTE_E, NOTE_HALF}, {NOTE_D, NOTE_WHOLE},
  {NOTE_C, NOTE_HALF}, {NOTE_C, NOTE_HALF}, {NOTE_G, NOTE_HALF}, {NOTE_G, NOTE_HALF}, {NOTE_A, NOTE_HALF}, {NOTE_A, NOTE_HALF}, {NOTE_G, NOTE_WHOLE},
  {NOTE_F, NOTE_HALF}, {NOTE_F, NOTE_HALF}, {NOTE_E, NOTE_HALF}, {NOTE_E, NOTE_HALF}, {NOTE_D, NOTE_HALF}, {NOTE_D, NOTE_HALF}, {NOTE_C, NOTE_WHOLE},
};

// This melody is playing all the notes of the octave from C up to B and back down to C

Note melody2[] = {
  {NOTE_C, NOTE_WHOLE}, {NOTE_CS, NOTE_WHOLE}, {NOTE_D, NOTE_WHOLE}, {NOTE_DS, NOTE_WHOLE}, {NOTE_E, NOTE_WHOLE}, {NOTE_F, NOTE_WHOLE}, {NOTE_FS, NOTE_WHOLE}, {NOTE_G, NOTE_WHOLE}, {NOTE_GS, NOTE_WHOLE}, {NOTE_A, NOTE_WHOLE}, {NOTE_AS, NOTE_WHOLE}, {NOTE_B, NOTE_WHOLE},
  {NOTE_AS, NOTE_WHOLE}, {NOTE_A, NOTE_WHOLE}, {NOTE_GS, NOTE_WHOLE}, {NOTE_G, NOTE_WHOLE}, {NOTE_FS, NOTE_WHOLE}, {NOTE_F, NOTE_WHOLE}, {NOTE_E, NOTE_WHOLE}, {NOTE_DS, NOTE_WHOLE}, {NOTE_D, NOTE_WHOLE}, {NOTE_CS, NOTE_WHOLE}, {NOTE_C, NOTE_WHOLE}
};

// Oh Susanna!
Note melody3[] = {
  {NOTE_C, NOTE_EIGHTH}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_A, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, DOTTED(NOTE_QUARTER)}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER},  {NOTE_E, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, {NOTE_D, DOTTED(NOTE_HALF)},
  {NOTE_C, NOTE_EIGHTH}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_G, DOTTED(NOTE_QUARTER)}, {NOTE_A, NOTE_EIGHTH}, {NOTE_G, NOTE_QUARTER}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, DOTTED(NOTE_QUARTER)}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER},  {NOTE_E, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_C, DOTTED(NOTE_HALF)},
  {NOTE_C, NOTE_EIGHTH}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_A, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, DOTTED(NOTE_QUARTER)}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER},  {NOTE_E, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, {NOTE_D, DOTTED(NOTE_HALF)},
  {NOTE_C, NOTE_EIGHTH}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_G, DOTTED(NOTE_QUARTER)}, {NOTE_A, NOTE_EIGHTH}, {NOTE_G, NOTE_QUARTER}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, DOTTED(NOTE_QUARTER)}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER},  {NOTE_E, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_C, NOTE_WHOLE},
  {NOTE_F, NOTE_HALF}, {NOTE_F, NOTE_HALF}, {NOTE_A, NOTE_QUARTER}, {NOTE_A, NOTE_HALF}, {NOTE_A, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, {NOTE_D, DOTTED(NOTE_HALF)},
  {NOTE_C, NOTE_EIGHTH}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER}, {NOTE_G, NOTE_QUARTER}, {NOTE_G, DOTTED(NOTE_QUARTER)}, {NOTE_A, NOTE_EIGHTH}, {NOTE_G, NOTE_QUARTER}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, DOTTED(NOTE_QUARTER)}, {NOTE_D, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER},  {NOTE_E, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_C, NOTE_WHOLE},
  
};

// Frere Jacques / Brother John
Note melody4[] = {
  {NOTE_C, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, {NOTE_D, NOTE_QUARTER}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, 
  {NOTE_E, NOTE_QUARTER}, {NOTE_F, NOTE_QUARTER}, {NOTE_G, NOTE_HALF}, {NOTE_E, NOTE_QUARTER}, {NOTE_F, NOTE_QUARTER}, {NOTE_G, NOTE_HALF}, 
  {NOTE_G, NOTE_EIGHTH}, {NOTE_A, NOTE_EIGHTH}, {NOTE_G, NOTE_EIGHTH}, {NOTE_F, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, {NOTE_G, NOTE_EIGHTH}, {NOTE_A, NOTE_EIGHTH}, {NOTE_G, NOTE_EIGHTH}, {NOTE_F, NOTE_EIGHTH}, {NOTE_E, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, 
  {NOTE_D, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, {NOTE_C, NOTE_HALF}, {NOTE_D, NOTE_QUARTER}, {NOTE_C, NOTE_QUARTER}, {NOTE_C, NOTE_HALF},
};

#define MELODY_LENGTH(m) (sizeof(m)/sizeof(m[0]))

Adafruit_MPR121 cap = Adafruit_MPR121();

// Keeps track of the last pins touched
// so we know when buttons are 'released'
uint16_t lasttouched = 0;
uint16_t currtouched = 0;
Button btnUP(UP_PIN), btnDN(DN_PIN);
void setup() {
  Serial.begin(9600);
btnUP.begin();
btnDN.begin();
  while (!Serial) { // needed to keep leonardo/micro from starting too fast!
    delay(10);
  }
  
  Serial.println(F("ProtoStax Piano Demo")); 
  
  // Default address is 0x5A, if tied to 3.3V its 0x5B
  // If tied to SDA its 0x5C and if SCL then 0x5D
  if (!cap.begin(0x5A)) {
    Serial.println(F("MPR121 not found, check wiring?"));
    while (1);
  }
  Serial.println(F("MPR121 found!"));
  playTune(melody2, 23, 48);
(melody2, 23, 48);
}

void loop() {
btnUP.read();
 btnDN.read();
 static int lastOctave = 4;
lastOctave = octaveNum;
 if (btnUP.wasPressed()) {
    octaveNum = 5;
 } else if (btnDN.wasPressed()) {
   octaveNum = 3; 
 } else {
   octaveNum = 4;
 
  currtouched = cap.touched();
  // Get the currently touched pads
  //currtouched = cap.touched();

  // Play tunes if our 'secret' combination of keys is pressed! 
  if (currtouched == 2193) { // C E G B
    playTune(melody, MELODY_LENGTH(melody), 2); // Play Twinkle Twinkle Little Star
 } else if (currtouched == 181) { // C D E F G
   playTune(melody2, MELODY_LENGTH(melody2), 48); // Play scale slide up and down
 } else if (currtouched == 2565) 
  { // C D A B
   playTune(melody3, MELODY_LENGTH(melody3), 1);
    // Play Oh Susanna!
  } else if (currtouched == 3075) { // C C# A# B
 playTune(melody4, MELODY_LENGTH(melody4), 1);  // Play Frere Jacques
  }  {

    for (uint8_t i=0; i<12; i++) {
      // if it *is* touched and *wasnt* touched before, play the corresponding tone!
      if ((currtouched & _BV(i)) && (!(lasttouched & _BV(i)) || (lastOctave != octaveNum) )) {
        // Serial.print("currtouched = "); Serial.print(currtouched); Serial.print(" lasttouched = "); Serial.print(lasttouched); Serial.print(" "); Serial.print(i); Serial.println(" touched");
        tone(TONE_PIN, scale[octaveNum][i]);
        
      }
      // if it *was* touched and now *isnt*, and additionally, no button is being pressed, then stop the tone
      // This allows for smooth transitions between notes as you slide you finger over the keys
      // This also allows for sustain of a given note, by touching any key and keeping it touched - you can press another key and it will play that key, but won't stop playing it 
      // until you let go of your first key - kind of like the sustain pedal of the piano!
      if (!(currtouched & _BV(i)) && (lasttouched & _BV(i)) && !currtouched) {
   //  if (!(currtouched & _BV(i)) && (lasttouched & _BV(i))) {
        // Serial.print("currtouched = "); Serial.print(currtouched); Serial.print(" lasttouched = "); Serial.print(lasttouched); Serial.print(" "); Serial.print(i); Serial.println(" released");
        noTone(TONE_PIN);      
      }
    }
  }

  // reset our state
  lasttouched = currtouched;
}

// This function is used to play a given melody
// Arguments are:
// array of Notes for the melody
// size of array
// speedup factor - higher number plays the melody faster

void playTune(Note *m, int mSize, int speedUp) {
  noTone(TONE_PIN); // Start with a clean slate
  for (int thisNote = 0; thisNote < mSize; thisNote++) {

    // to calculate the note duration, take one second multiplies by the note type.
    //e.g. quarter note = 1000.0 * 0.25, eighth note = 1000 * 1/8 (0.125), etc.
    // reduce the duration by the speedup factor to increase the speed of playing 
    // by an appropriate amount
    int noteDuration = 1000.0 * m[thisNote].duration / speedUp;
    tone(TONE_PIN, m[thisNote].frequency, noteDuration);

    // to distinguish the notes, set a minimum time between them.
    // the note's duration + 30% seems to work well:
    int pauseBetweenNotes = noteDuration * 1.30;
    delay(pauseBetweenNotes);
    // stop the tone playing:
    noTone(TONE_PIN);
  }
  delay(100);
  
}

**Comment by sridharrajagopal** [comment]
Hi there, 

There are actually multiple errors - only one of them is listed as a possible reason at the end. I've highlighted all the "errors" from your output: 


ProtoStax_CapacitiveTouch_Piano_Demo:171:3: **error**: 'playTune' was not declared in this scope
   playTune(melody2, 23, 48);
   ^~~~~~~~

ProtoStax_CapacitiveTouch_Piano_Demo:193:5: **error**: 'playTune' was not declared in this scope
     playTune(melody, MELODY_LENGTH(melody), 2); // Play Twinkle Twinkle Little Star
     ^~~~~~~
ProtoStax_CapacitiveTouch_Piano_Demo:195:4: **error**: 'playTune' was not declared in this scope

ProtoStax_CapacitiveTouch_Piano_Demo:198:4: **error**: 'playTune' was not declared in this scope

ProtoStax_CapacitiveTouch_Piano_Demo:201:2: **error**: 'playTune' was not declared in this scope

ProtoStax_CapacitiveTouch_Piano_Demo:233:48: **error**: a function-definition is not allowed here before '{' token
                                                ^
ProtoStax_CapacitiveTouch_Piano_Demo:253:1: **error**: expected '}' at end of input
 }
 ^
exit status 1
'playTune' was not declared in this scope

**Comment by sridharrajagopal** [comment]
In your code that you sent, in the loop() function

```
void loop()
{
....
 if (btnUP.wasPressed()) {
    octaveNum = 5;
 } else if (btnDN.wasPressed()) {
   octaveNum = 3;
 } else {
   octaveNum = 4;

```
 
You are missing the closing brace } for the else statement. This is the problem. It throws the compiler for a loop because all the stuff after it is interpreted incorrectly, which is why you see so many errors. The compiler also shows in the exit status the latest error (shown first) (in your case 'playTune' was not declared in this scope), which is not the actual problem - the actual problem is the first error, usually at the end, which in your case is 

ProtoStax_CapacitiveTouch_Piano_Demo:253:1: error: expected '}' at end of input
}

If you add the extra closing brace } after the else statement as is expected, you should be find (provided there are no other errors). 

-Sridhar

**Comment by sridharrajagopal** [comment]
Let me know if it worked after adding the closing } 

Thanks,
Sridhar

**Comment by lschotz** [comment]
Yes it is working now that’s for all the help

Larry

**Comment by sridharrajagopal** [comment]
Documentation updated to show JC_Button library is required. 

https://github.com/protostax/ProtoStax_CapacitiveTouch_Piano_Demo/commit/ecd72aae532f7abd076a898a40696c1554fb2574
